version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  django:
    build: ./app
    command: >
      sh -c "
      echo 'Waiting for PostgreSQL to start...';    
      while ! nc -z db 5432; do
        sleep 1;
      done;
      echo 'PostgreSQL started';
      python manage.py migrate;
      gunicorn shopproject.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static_volume:/app/static
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume: