# Generated by Django 5.2.1 on 2025-07-06 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_available_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Сорт', 'verbose_name_plural': 'Сорта'},
        ),
        migrations.AddField(
            model_name='product',
            name='abv',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Крепость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ibu',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True, verbose_name='IBU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
