# Generated by Django 5.2.1 on 2025-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_product_abv_product_ibu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Крепость'),
        ),
    ]
