# Generated by Django 5.2.1 on 2025-07-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('pick_up_point', 'Пункт выдачи'), ('delivery', 'Курьерская доставка'), ('mail_rf', 'Почта России')], default='самовыыоз', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='pyment',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card_online', 'Картой онлайн'), ('card_courier', 'Картой курьеру')], default='картой', max_length=50),
        ),
    ]
