# Generated by Django 5.2.1 on 2025-07-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_likeuser_likeitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeitem',
            old_name='cart',
            new_name='like',
        ),
    ]
