# Generated by Django 5.2.1 on 2025-07-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0002_alter_order_delivery_alter_order_pyment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pyment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='картой', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cartuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(default='самовывоз из магазина', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(editable=False, max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
